### PR TITLE
Update IoTHub.md

### PR DESCRIPTION
**Pull request by gjswalling**
need to also add "global.azure-devices-provisioning.net" in "AllowedConnections" for DPS

### CODE REVIEW

**Comment by richardtaylorrt** [comment]
Many thanks for raising this.  We ended up pushing a different and bigger set of changes that also fixes this, so closing this out with our thanks.

**Comment by floresboy** [comment]
Hi Richard,

While working on a tech demonstrator where we swapped NodeMCU devices for proper secure hardware in the form of Azure sphere we run into lots of errors in de Sphere sample code. While first Inet connectifity seemed the problem it’s not anymore. We had to alter several examples and then they worked (a bit). One example is the HTTPS_Curl_Easy <https://github.com/Azure/azure-sphere-samples/blob/master/Samples/HTTPS/HTTPS_Curl_Easy>  where we had to remove the wlan InterFaceState check in line 260. Also in that same example the httPS get-request did not work (cert could not be found errors) but httP worked fine. Does that mean the sample files are incorrect or are we doing something worng ?

Same applied to the Azure-IoT code: while we did the complete setup a couple of times as instructed (on both Windows10 (VS studio, and VS Code setups)  and Linux) we keep on getting ‘handover errors’. We realy need this simple thing to work.

I would be a shame we have to leave this wonderful secure IoT technology simply because we can’t get out tech demo not working and as a result we’re losing internal support for the idea. Can you/MS please help us ?



Met vriendelijke groet, (k.straatman@home.nl)

Kamiel Straatman | Digital Innovation Specialist EMEA | Insight Enterprises Netherlands B.V.
t. +31 (0)55 5492410 | m. +31 (0)6 18 79 74 79 | kamiel.straatman@insight.com <mailto:kamiel.straatman@insight.com> | nl.insight.com <http://www.uk.insight.com/>

**Comment by richardtaylorrt** [comment]
Hi @floresboy - we're more than happy to help with this.  The samples should just work for you, and it's an important issue for us if they don't.  To help us help you, I'd like to ensure we have live issues for each problem (this thread is a closed PR!)

1. HTTPS_Curl_Easy. I assume this is [this issue](https://github.com/Azure/azure-sphere-samples/issues/109).  From what I can see you aren't doing anything wrong.  HTTPS should work.  You shouldn't need to delete any code.  I hear that someone reached out personally to support you on this issue today.
2. Azure IoT.  I've not seen "handover errors" before.  Please could you raise a new issue, with the precise steps you performed, and a paste of all the errors you are seeing.
3. Were there other errors in other samples too?

I will soon be leaving for the holidays, as will many of my colleagues, but I very much hope we can figure out all these problems for you rapidly in the new year.

**Comment by floresboy** [comment]
Hi Richard,

Thanks for getting back

the issue is actually this one: https://github.com/Azure/azure-sphere-samples/issues/105 

>> I hear that someone reached out personally to support you on this issue today.
Yes, thanks for that, i just responded to Vishnu.

I’ll raise another issue on the IoT errors.

Thanks again, have great holidays!

Best, Kamiel

**Pull request closed without merging**
