### PR TITLE
Add `$schema` to `cgmanifest.json`

### PR DESCRIPTION
**Pull request by JamieMagee**
This pull request adds the JSON schema for `cgmanifest.json`.

### Why?

A JSON schema helps you to ensure that your `cgmanifest.json` file is valid.
JSON schema validation is a build-in feature in most modern IDEs like Visual Studio and Visual Studio Code.
Most modern IDEs also provide code-completion for JSON schemas.

### How can I validate my `cgmanifest.json` file?

Most modern IDEs like Visual Studio and Visual Studio Code have a built-in feature to validate JSON files.
You can also use [this small script](https://github.com/JamieMagee/verify-cgmanifest) to validate your `cgmanifest.json` file.

### Why does it suggest camel case for the properties?

Component Detection is able to read camel case and pascal case properties.
However, the JSON schema doesn't have a case-insensitive mode.
We therefore suggest camel case as it's the most common format for JSON.

### Why is the diff so large?

To deserialize the `cgmanifest.json` file, we use [`JSON.parse()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse).
However, to serialize the JSON again we use [`prettier`](https://prettier.io/).
We found that, in general, it gave smaller diffs than the default [`JSON.stringify()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) function.

### CODE REVIEW

**Comment by jamesadevine** [comment]
@JamieMagee why is this change required to the current cgmanifest file? 

The PR seems to change the structure in addition to adding a schema. Will this impact customers on older VS/VS code versions?

**Comment by JamieMagee** [comment]
@jamesadevine it's not a required change, but more of a quality-of-life improvement. A JSON schema allows you to quickly verify that your `cgmanifest.json` is valid.

`cgmanifest.json` is used with Component Governance and should have no impact to external customers. See [our documentation][1] for more information. There are some whitespace changes, but if you view the diff without whitespace changes, only the `$schema` property was added.

[1]: https://docs.opensource.microsoft.com/tools/cg/features/cgmanifest/

**Comment by jamesadevine** [comment]
Hi @JamieMagee thanks for the clarifications!

Due to organisational policies, I have to run code changes (no matter how small or minor) through the internal version of this repository first. 

Hope that's ok!

**Comment by jamesadevine** [comment]
@JamieMagee I've updated the `cgmanifest.json` file with the changes suggested in the latest release. Please see: https://github.com/Azure/azure-sphere-samples/blob/main/Samples/DeviceToCloud/ExternalMcuLowPower/McuSoda/cgmanifest.json

Thank you for drawing attention to this :smile:

**Pull request closed without merging**
