### PR TITLE
WriteIntegerAsStringWithBaseWidth bugfix

### PR DESCRIPTION
**Pull request by dougboling**
Fixed WriteIntegerAsStringWithBaseWidth to properly render hex numbers.

### CODE REVIEW

**Comment by cjoprey** [comment]
Hi Doug,

Thank you for the PR you submitted. We are reviewing this now, and would like to ask if you could provide one or more examples, with the output they generate, that show how the existing code is failing for non-decimal bases.

Best regards,
Chris O'Prey

**Comment by cjoprey** [comment]
Hi Doug,

We have not heard any further information from you regarding our request for examples that show the issue you mentioned. Can you confirm if there is still an issue, and if o, provide us with clear example code and the failing output?

Many thanks,
Chris.

**Comment by dougboling** [comment]
Been pulled away on other tasks. I’ll try to get something soon. 

 

The simple answer is to call the function with base 16 and the MSB set you’ll get a negative sign prefixing the hex output. 

 

Doug

**Comment by cawhitworth** [comment]
This PR refers to a now-deprecated sample; closing.

**Pull request closed without merging**
